language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_deploy:
- git config --local user.name "NioXen"
- git config --local user.email "bgibbonsdev@gmail.com"
before_script:
- npm run build
script:
- npm run test
after_success:
- npm run coverage
- npm run pack
deploy:
  - provider: npm
    skip_cleanup: true
    email: bgibbonsdev@gmail.com
    api_key:
      secure: YppuuRHmuO9cX9b8TrJSsiVsnip8UcokQ2CQsBufGfpdG6CWYZ6VLhf/2AwKtfO7oc7utesZsTmhq4k+4MmmRHAEpAO+ydnkFgPz3YQc09HTVlGG7whXpJYqVumvfNzfMocbnb6lHVvg25XO6xuRQNR+GL5Iomk9MuK3WM30soWTtMnkhHvZpezNrRtVaLAmRv2vhXEVWQ2qZ0VNkiJPrWUaSAuGxy0WwGnCb8Q5cIVhvhOYwhAnW+V1oU1zdR6o9v8HVlPa/KghbAAwXKmx4+t+v5m1dl5MoNWx09N4Yy2jYP4IKA7UbXZqyTJMuwiRJVau51/xVKvrFj31+JPm2IJVB/3cHu7MG0urwbwR0IJ9zT2EzTd1iUYTSw4Zi3KtU9WoabpMd+jXR7GoEyOZQvR8fTVDyU+ZNCeFovxaNiMMvERgALwdgDh08Qq5JtwIHYNpsOk/KvIuEmT8Us+JcAXF16FvT3bCWk13nZE2eikSksd95QaMgmlnlNo6twPJd74+qg102imY7GynvdMzkzx3jHvGbrUTd0KHVzOedVJVpfxk9hU3dfhy3S9O/9DxP2EGm4Ev9ltEOZiMVpwJwXhfpkuak9o7pKuPMILIzSWqJ6zhepO+pUv/NaVgTW/AnR7c3Q6MqIEOwS8BG9KkI1/TdU/2/Hc+464waGlk7tY=
    on:
      repo: NioXen/typesafe-mapper
      tags: true
  - provider: releases
    api_key:
      secure: bOrlsiqGVJ1loYW7b/gMsykZsX/R7dTN5BbldtEdvbUs92/QFKpjtH7yRCojLkI1RI2uKQ3l225VE4ZAEnUXMb3/oN6eSYfCPOXeYCfBLwUMkXu6w7Np5tkX6Zd4j8QpsEVNCzDBlZaBUmw4caVuGTwGuhXF5YlLBukJYRymhSf1ohubVNN5MTGm4Qym4glBc3ubAui5UPkLmnRg9VIyZSzWki20ganc/Hwo+14lWlRzBgJdgIA63E9DyuGLQdldQAd6GwaAV2ssjPvWxfmMaAO1HwJr4K2q93jzskjmzz7rtpsubtbmtlwmPTDJMU94g9TSCJ5I6Dnn2WdUjTJCx4PqrLIvpcvqkNzKimheHQnoZ11DAGoZnRnwEg4HGg7mM9tbAfsH9YPMcbKxKFJD+HZ9yry8Mvuf+sOD8dRqXJj+w+c0iGeC15AmBs/YiKBA2Fn8XOwLY8iSTr7Mzm4WDhMYKAF/weZIId7rE7NXk5JQ2KCg0FDVz5pocn82y7RtC7oecCk1vTz+wG+trXUPsi/jxR2GPeNBvQ2J9w/QqU3RgqKwBH4JP3M7Fp8MSYZHhqzwAEG8GXW71wt35gikJgtdOdTbIEIcmqJKxcsYNCI5eH290uClQ2lfwXPdIbjM/lupqFP+EuAezvC5MzdJmgdSAqO0rH4ZGoZNF/LcEhI=
    file: typesafe-mapper-*.tgz
    skip_cleanup: true     
    on:
      repo: NioXen/typesafe-mapper
      tags: true